# Generated by Django 5.0.6 on 2024-06-08 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fruits', 'Фрукты'), ('vegetables', 'Овощи'), ('vehicles', 'Транспортные средства'), ('appliances', 'Бытовые приборы'), ('animals', 'Животные'), ('plants', 'Растения')], max_length=20)),
                ('category_slug', models.SlugField(blank=True, max_length=20)),
                ('task_type', models.CharField(choices=[('word_scramble', 'Перемешанные буквы'), ('image_match', 'Сопоставление изображения и слова'), ('action_description', 'Описание действия'), ('word_assembly', 'Составление слова из обрывков')], max_length=20)),
                ('task_type_slug', models.SlugField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fruits', 'Фрукты'), ('vegetables', 'Овощи'), ('vehicles', 'Транспортные средства'), ('appliances', 'Бытовые приборы'), ('animals', 'Животные'), ('plants', 'Растения')], max_length=100)),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('correct', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
