# Generated by Django 5.0.6 on 2024-06-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_motivationalphrase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='wordimage',
            name='image_data',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordimage',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
