# Generated by Django 5.0.6 on 2024-06-13 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_wordimage_image_data_wordimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActionImageTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='action_image_tasks/')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.action')),
                ('person_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.persontype')),
            ],
        ),
    ]
