# Generated by Django 5.0.6 on 2024-06-13 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_action_persontype_actionimagetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='action_image_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.actionimagetask'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
